# kubectl create secret docker-registry reg-cred-secret --docker-server="docker-registry:30001" --docker-username=admin --docker-password=Netapp1! --dry-run=client -o yaml

apiVersion: v1
kind: Secret
metadata:
  name: reg-cred-secret
  namespace: netapp-acc
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItcmVnaXN0cnk6MzAwMDEiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiTmV0YXBwMSEiLCJhdXRoIjoiWVdSdGFXNDZUbVYwWVhCd01TRT0ifX19
