apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra 
  namespace: netapp-acc
spec:
  accountName: "Demo"
  astraVersion: "24.02.0-69"
  astraAddress: "astra.demo.netapp.com"
  autoSupport:
    enrolled: false
  email: "admin@demo.netapp.com"
  firstName: "SRE"
  lastName: "Admin"
  volumeReclaimPolicy: "Delete" #maybe change this to Retain
  scaleSize: Small
  astraResourcesScaler: "Off"
  ingressType: "AccTraefik"  
  imageRegistry:
    name: "192.168.0.61:30001/netapp/acc/24.02.0-69"
    secret: "reg-cred-secret"
  storageClass: "c1-svmacc-nas-basic"
  additionalValues: {}
  crds:
    externalTraefik: false
    externalCertManager: false
