apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra 
  namespace: netapp-acc
spec:
  accountName: "Demo"
  astraVersion: "22.08.0-20"
  astraAddress: "astra.demo.netapp.com"
  autoSupport:
    enrolled: false
  email: "admin@demo.netapp.com"
  firstName: "SRE"
  lastName: "Admin"
  ingressType: "AccTraefik"  
  imageRegistry:
    name: "docker-registry:30001/netapp/astracc/22.08.0-20"
    secret: "reg-cred-secret"
  storageClass: "nas-basic"
