#Example REST API calls using the REST CLIENT extension 
#available from the VScode marketplace

#Global Variables 
#NOTE: These values will not work work in your environment
#They must be changed

@contentType = application/json
@baseUrl = https://astra.demo.netapp.com
@token = 0gD06KBeFdHwMUwd9mCBE5YrfwIcCv3g1MptJy4pPtg=
@defaultAccountId = 3556a25f-f8a5-4312-88cf-809f49f530a6
@managedClusterId = ed68edf7-7cd1-483f-9074-62ac94c0d75b
@defaultStorageClassId = a41d4a0d-39b5-47e7-9948-51b2e2c0f587
@managedAppId = a2cce840-9649-4293-afad-953e7ff3d151
@managedAppBackupId = 4f2d5fba-0c13-4ad5-9ce9-e0d630367ac4

###Step 2-10 List accounts
GET {{baseUrl}}/accounts
Accept: {{contentType}}
Authorization: Bearer {{token}}

###Step 2-14 List account users with parameters
GET {{baseUrl}}/accounts/{{defaultAccountId}}/core/v1/users
 ?include=firstName,lastName,id
Accept: {{contentType}}
Authorization: Bearer {{token}}

###Step 2-17 Get managed clusters
GET {{baseUrl}}/accounts/{{defaultAccountId}}/topology/v1/managedClusters
Accept: {{contentType}}
Authorization: Bearer {{token}}

###Step 2-20 Get the storage classes for a managed cluster
GET {{baseUrl}}/accounts/{{defaultAccountId}}/topology/v1/managedClusters/{{managedClusterId}}/storageClasses
Accept: {{contentType}}
Authorization: Bearer {{token}}

###Step 2-24 Update the default storage class for a managed cluster
PUT {{baseUrl}}/accounts/{{defaultAccountId}}/topology/v1/managedClusters/{{managedClusterId}}
Accept: {{contentType}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "type": "application/astra-managedCluster",
    "version": "1.0",
    "defaultStorageClass": "{{defaultStorageClassId}}"

}

###Step 2-30 List managed apps
GET {{baseUrl}}/accounts/{{defaultAccountId}}/topology/v2/managedClusters/{{managedClusterId}}/apps
 ?include=name,id
Accept: {{contentType}}
Authorization: Bearer {{token}}

###Step 2-33 Get the backups for a managed app
GET {{baseUrl}}/accounts/{{defaultAccountId}}/k8s/v1/apps/{{managedAppId}}/appBackups
Accept: {{contentType}}
Authorization: Bearer {{token}}

###Step 2-36 Create a backup for a managed app
POST {{baseUrl}}/accounts/{{defaultAccountId}}/k8s/v1/apps/{{managedAppId}}/appBackups
Accept: {{contentType}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "type": "application/astra-appBackup",
    "version": "1.1"
}

###Step 2-49 Get the backup status
GET {{baseUrl}}/accounts/{{defaultAccountId}}/k8s/v1/apps/{{managedAppId}}/appBackups/{{managedAppBackupId}}
Accept: {{contentType}}
Authorization: Bearer {{token}}

###Step 2-50 Delete the backup 
DELETE {{baseUrl}}/accounts/{{defaultAccountId}}/k8s/v1/apps/{{managedAppId}}/appBackups/{{managedAppBackupId}}
Accept: {{contentType}}
Authorization: Bearer {{token}}