apiVersion: v1
kind: Secret
metadata:
  name: ontap-cluster1-admin
  namespace: gateway
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Netapp1!
---
apiVersion: v1
kind: Secret
metadata:
  name: ontap-svmsource-admin
  namespace: gateway
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: gateway.netapp.com/v1alpha2
kind: StorageVirtualMachine
metadata:
  name: svmsource
  namespace: gateway
spec:
  svmName: svmsource
  clusterHost: 192.168.0.101
  debug: false
  aggregates:
  - name: Cluster1_01_FC_1
  management:
    name: manage1
    ip: 192.168.0.40
    netmask: 255.255.255.0
    broadcastDomain: Default
    homeNode: Cluster1-01
  vsadminCredentials:
    name: ontap-svmsource-admin
    namespace: gateway
  clusterCredentials:
    name: ontap-cluster1-admin
    namespace: gateway
  nfs:
    enabled: true
    v3: true
    v4: true
    v41: true
    interfaces:
    - name: nfs1
      ip: 192.168.0.41
      netmask: 255.255.255.0
      broadcastDomain: Default
      homeNode: Cluster1-01
    export:
      name: default
      rules:
      - clients: 0.0.0.0/0
        protocols: any
        rw: any
        ro: any
        superuser: any
        anon:  "65534"
  iscsi:
    enabled: true
    alias: svmsource
    interfaces:
    - name: iscsi1
      ip: 192.168.0.42
      netmask: 255.255.255.0
      broadcastDomain: Default
      homeNode: Cluster1-01
    - name: iscsi2
      ip: 192.168.0.43
      netmask: 255.255.255.0
      broadcastDomain: Default
      homeNode: Cluster1-01