apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-basic
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  backendType: ontap-nas
  fsType: nfs
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: san-basic
provisioner: csi.trident.netapp.io
parameters:
  backendType: ontap-san