apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: c1-svmacc-nas-basic
provisioner: csi.trident.netapp.io
parameters:
  storagePools: "c1-svmacc-ontap-nas-backend:.*"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: c1-svmacc-san-basic
provisioner: csi.trident.netapp.io
parameters:
  storagePools: "c1-svmacc-ontap-san-backend:.*"