apiVersion: v1
kind: Secret
metadata:
  name: c1-svmsource-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: change_me
  password: change_me
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c1-svmsource-nas-backend
  namespace: trident
spec:
  version: 1
  backendName: c1-svmsource-ontap-nas-backend
  storageDriverName: ontap-nas
  replicationPolicy: MirrorAllSnapshots
  managementLIF: change_me
  dataLIF: change_me
  svm: change_me
  credentials:
    name: c1-svmsource-backend-secret
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c1-svmsource-san-backend
  namespace: trident
spec:
  version: 1
  backendName: c1-svmsource-ontap-san-backend
  replicationPolicy: MirrorAllSnapshots
  storageDriverName: ontap-san
  managementLIF: change_me
  dataLIF: change_me
  svm: change_me
  credentials:
    name: c1-svmsource-backend-secret