apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: c2-svmacc-nas-basic
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  storagePools: "c2-svmacc-ontap-nas-backend:.*"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: c2-svmacc-san-basic
provisioner: csi.trident.netapp.io
parameters:
  storagePools: "c2-svmacc-ontap-san-backend:.*"