apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-operator
  namespace: trident
  labels:
    app: operator.trident.netapp.io
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: trident-operator
      app: operator.trident.netapp.io
  template:
    metadata:
      labels:
        name: trident-operator
        app: operator.trident.netapp.io
    spec:
      serviceAccountName: trident-operator
      containers:
        - name: trident-operator
          image: netapp/trident-operator:22.07.0
          command:
          - "/trident-operator"
          - "--debug"
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "trident-operator"
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
