kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-basic
  namespace: default
  labels:
    test: nfs-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nas-basic
---
kind: Pod
apiVersion: v1
metadata:
  name: nfs-pod
  namespace: default
  labels:
    test: nfs-web
spec:
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
       claimName: nfs-basic
  containers:
    - name: nfs-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nfs-storage
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-web
  namespace: default
  labels:
    test: nfs-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    test: nfs-web