apiVersion: v1
kind: Secret
metadata:
  name: svm0-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: nas-backend
  namespace: trident
spec:
  version: 1
  backendName: ontap-nas-backend
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.30
  dataLIF: 192.168.0.31
  svm: svm0
  credentials:
    name: svm0-backend-secret
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: san-backend
  namespace: trident
spec:
  version: 1
  backendName: ontap-san-backend
  storageDriverName: ontap-san
  managementLIF: 192.168.0.30
  dataLIF: 192.168.0.32
  svm: svm0
  credentials:
    name: svm0-backend-secret