apiVersion: v1
kind: Secret
metadata:
  name: c1-svm0-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c1-nas-backend
  namespace: trident
spec:
  version: 1
  backendName: c1-ontap-nas-backend
  storageDriverName: ontap-nas
  replicationPolicy: MirrorAllSnapshots
  managementLIF: 192.168.0.30
  dataLIF: 192.168.0.31
  svm: svm0
  credentials:
    name: c1-svm0-backend-secret
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c1-san-backend
  namespace: trident
spec:
  version: 1
  backendName: c1-ontap-san-backend
  replicationPolicy: MirrorAllSnapshots
  storageDriverName: ontap-san
  managementLIF: 192.168.0.30
  dataLIF: 192.168.0.32
  svm: svm0
  credentials:
    name: c1-svm0-backend-secret