apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tridentorchestrators.trident.netapp.io
spec:
  group: trident.netapp.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
  names:
    kind: TridentOrchestrator
    listKind: TridentOrchestratorList
    plural: tridentorchestrators
    singular: tridentorchestrator
    shortNames:
    - torc
    - torchestrator
  scope: Cluster
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: trident
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: trident-operator
  labels:
    app: operator.trident.netapp.io
rules:
  # Permissions same as Trident
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims/status
    verbs:
      - update
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - resourcequotas
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments/status
    verbs:
      - update
      - patch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
      - volumesnapshotclasses
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots/status
      - volumesnapshotcontents/status
    verbs:
      - update
      - patch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotcontents
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - csi.storage.k8s.io
    resources:
      - csidrivers
      - csinodeinfos
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csidrivers
      - csinodes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - trident.netapp.io
    resources:
      - tridentversions
      - tridentbackends
      - tridentstorageclasses
      - tridentvolumes
      - tridentvolumepublications
      - tridentnodes
      - tridenttransactions
      - tridentsnapshots
      - tridentbackendconfigs
      - tridentbackendconfigs/status
      - tridentmirrorrelationships
      - tridentmirrorrelationships/status
      - tridentsnapshotinfos
      - tridentsnapshotinfos/status
      - tridentprovisioners # Required for Tprov
      - tridentprovisioners/status # Required to update Tprov's status section
      - tridentorchestrators # Required for Torc
      - tridentorchestrators/status # Required to update Torc's status section
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - tridentpods
  # Now Operator specific permissions
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - delete
      - update
      - patch
    resourceNames:
      - trident-csi
      - trident
  - apiGroups:
      - ""
    resources:
      - pods/exec
      - services
      - serviceaccounts
    verbs:
      - list
      - create
  - apiGroups:
      - ""
    resources:
      - pods/exec
      - services
      - serviceaccounts
    verbs:
      - delete
      - update
      - patch
    resourceNames:
      - trident-csi
      - trident
  - apiGroups:
      - authorization.openshift.io
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - list
      - create
  - apiGroups:
      - authorization.openshift.io
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - delete
      - update
      - patch
    resourceNames:
      - trident-csi
      - trident
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - list
      - create
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - tridentpods
    verbs:
      - delete
      - update
      - patch
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - trident
    verbs:
      - delete
      - update
      - patch
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - tridentoperatorpods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trident-operator
  namespace: trident
  labels:
    app: operator.trident.netapp.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trident-operator
  labels:
    app: operator.trident.netapp.io
subjects:
- kind: ServiceAccount
  name: trident-operator
  namespace: trident
roleRef:
  kind: ClusterRole
  name: trident-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: tridentoperatorpods
  labels:
    app: operator.trident.netapp.io
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - projected
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-operator
  namespace: trident
  labels:
    app: operator.trident.netapp.io
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: trident-operator
      app: operator.trident.netapp.io
  template:
    metadata:
      labels:
        name: trident-operator
        app: operator.trident.netapp.io
    spec:
      serviceAccountName: trident-operator
      containers:
        - name: trident-operator
          image: netapp/trident-operator:22.07.0
          command:
          - "/trident-operator"
          - "--debug"
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "trident-operator"
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
---
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident