apiVersion: v1
kind: Secret
metadata:
  name: c2-svmdest-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: change_me
  password: change_me
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c2-svmdest-nas-backend
  namespace: trident
spec:
  version: 1
  backendName: c2-svmdest-ontap-nas-backend
  storageDriverName: ontap-nas
  replicationPolicy: MirrorAllSnapshots
  managementLIF: change_me
  dataLIF: change_me
  svm: change_me
  credentials:
    name: c2-svmdest-backend-secret
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c2-svmdest-san-backend
  namespace: trident
spec:
  version: 1
  backendName: c2-svmdest-ontap-san-backend
  storageDriverName: ontap-san
  replicationPolicy: MirrorAllSnapshots
  managementLIF: change_me
  dataLIF: change_me
  svm: change_me
  credentials:
    name: c2-svmdest-backend-secret