apiVersion: v1
kind: Secret
metadata:
  name: c2-svm0-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: change_me
  password: change_me
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c2-nas-backend
  namespace: trident
spec:
  version: 1
  backendName: c2-ontap-nas-backend
  storageDriverName: ontap-nas
  managementLIF: change_me
  dataLIF: change_me
  svm: svm0
  credentials:
    name: c2-svm0-backend-secret
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c2-san-backend
  namespace: trident
spec:
  version: 1
  backendName: c2-ontap-san-backend
  storageDriverName: ontap-san
  managementLIF: change_me
  dataLIF: change_me
  svm: svm0
  credentials:
    name: c2-svm0-backend-secret